#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: connect Sanity CMS + deploy to Vercel for the portfolio.
# Run this from the portfolio/ directory:  bash setup-cms.sh
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE=".env.local"

banner "Portfolio · Sanity CMS + Vercel setup"

# ── Stage 1: create the Sanity project ────────────────────────────────────
stage "Sanity — create your project"
say "This holds all your editable content and images."
open_url "https://www.sanity.io/manage"
step "Click 'Create new project'. Name it (e.g. 'Ana Portfolio'), plan = Free."
step "Open the project → Datasets → add a dataset named 'production' (Public)."
step "Go to Settings → API and copy the Project ID (a short id like 'ab12cd34')."
ask NEXT_PUBLIC_SANITY_PROJECT_ID "Paste your Project ID:"
write_env NEXT_PUBLIC_SANITY_PROJECT_ID "$NEXT_PUBLIC_SANITY_PROJECT_ID"

# ── Stage 2: local environment (dataset, api version, webhook secret) ─────
stage "Local environment"
say "Writing the dataset + API version, and generating your webhook secret."
write_env NEXT_PUBLIC_SANITY_DATASET "production"
write_env NEXT_PUBLIC_SANITY_API_VERSION "2024-10-01"
SANITY_REVALIDATE_SECRET="$(_existing SANITY_REVALIDATE_SECRET || openssl rand -hex 32)"
write_env SANITY_REVALIDATE_SECRET "$SANITY_REVALIDATE_SECRET"
note "After this wizard, restart 'npm run dev' so the site switches from"
note "placeholder content to your live Sanity data."
pause

# ── Stage 3: CORS for local development ───────────────────────────────────
stage "Sanity — allow your local site (CORS)"
open_url "https://www.sanity.io/manage/project/${NEXT_PUBLIC_SANITY_PROJECT_ID}/api"
step "Under 'CORS origins' click 'Add CORS origin'."
step "Origin: http://localhost:3001   —   Allow credentials: ON   —   Save."
pause "Press Enter once the localhost origin is saved"

# ── Stage 4: add content in the Studio ────────────────────────────────────
stage "Add your content in the Studio"
note "Make sure 'npm run dev' is running in another terminal first."
open_url "http://localhost:3001/studio"
step "Sign in with Sanity (same account)."
step "Site settings: upload your résumé PDF, hero image, logos, socials, email."
step "Create each Project: title, description, tags, cover, hero image, the"
step "  context/role/problem/solution texts, up to 5 tool logos, gallery images."
step "Publish every document (the green Publish button)."
pause "Press Enter once your content is published"

# ── Stage 5: push code to GitHub ──────────────────────────────────────────
stage "Push the code to GitHub"
open_url "https://github.com/new"
step "Create a new empty repo (e.g. 'portfolio'). Do NOT add a README/.gitignore."
step "Copy its remote URL (https://github.com/you/portfolio.git or the SSH one)."
ask GIT_REMOTE "Paste the repo URL:"
if confirm "Commit all changes and push to that repo now?"; then
  git add -A
  git commit -m "Portfolio site + Sanity CMS" || note "nothing new to commit"
  git remote remove origin >/dev/null 2>&1 || true
  git remote add origin "$GIT_REMOTE"
  git branch -M main
  git push -u origin main || warn "push failed — check the URL/auth and run 'git push -u origin main' manually"
else
  SKIPPED+=("git push to $GIT_REMOTE (run: git push -u origin main)")
fi

# ── Stage 6: deploy on Vercel ─────────────────────────────────────────────
stage "Deploy on Vercel"
open_url "https://vercel.com/new"
step "Import the GitHub repo you just pushed (framework auto-detects as Next.js)."
step "Expand 'Environment Variables' and add these four (name = value):"
say ""
say "  NEXT_PUBLIC_SANITY_PROJECT_ID   = ${NEXT_PUBLIC_SANITY_PROJECT_ID}"
say "  NEXT_PUBLIC_SANITY_DATASET      = production"
say "  NEXT_PUBLIC_SANITY_API_VERSION  = 2024-10-01"
say "  SANITY_REVALIDATE_SECRET        = ${SANITY_REVALIDATE_SECRET}"
say ""
step "Click Deploy, wait for it to finish, then copy the production URL."
ask VERCEL_URL "Paste your live URL (https://<name>.vercel.app):"
write_env NEXT_PUBLIC_SITE_URL "$VERCEL_URL"

# ── Stage 7: CORS for the production URL ──────────────────────────────────
stage "Sanity — allow your live site (CORS)"
open_url "https://www.sanity.io/manage/project/${NEXT_PUBLIC_SANITY_PROJECT_ID}/api"
step "Add another CORS origin: ${VERCEL_URL}   —   Allow credentials: ON   —   Save."
pause "Press Enter once the production origin is saved"

# ── Stage 8: webhook for instant updates ──────────────────────────────────
stage "Sanity — webhook for instant updates"
open_url "https://www.sanity.io/manage/project/${NEXT_PUBLIC_SANITY_PROJECT_ID}/api/webhooks"
step "Create webhook. Name: 'Revalidate'. Dataset: production."
step "URL:  ${VERCEL_URL}/api/revalidate"
step "Trigger on: Create, Update, Delete.   HTTP method: POST."
step "Secret: paste the value below.   Enable, then Save."
say ""
say "  Secret = ${SANITY_REVALIDATE_SECRET}"
say ""
note "The default payload already includes _type, which the endpoint needs."
pause "Press Enter once the webhook is saved"

finish
note "Live site:   ${VERCEL_URL:-<your vercel URL>}"
note "Edit content at:   ${VERCEL_URL:-<your vercel URL>}/studio   (or /studio locally)"
note "Publishing in the Studio now updates the live site within a second or two."
printf '\n'
